runtime: python39

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /adios
    static_files: adios.html
    upload: adios.html

  - url: /imagenes
    static_dir: imagenes
